/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
/*
*   PSoCGPIOINT.h
*   Data: 04 June, 2002
*   Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
*
*  This file is generated by the Device Editor on Application Generation.
*  It contains equates that are useful in writing code relating to GPIO
*  related values.
*  
*  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
*  Edits to this file will not be preserved.
*/
// Port_0_4 address and mask defines
#pragma	ioport	Port_0_4_Data_ADDR:	0x0
BYTE			Port_0_4_Data_ADDR;
#pragma	ioport	Port_0_4_DriveMode_0_ADDR:	0x100
BYTE			Port_0_4_DriveMode_0_ADDR;
#pragma	ioport	Port_0_4_DriveMode_1_ADDR:	0x101
BYTE			Port_0_4_DriveMode_1_ADDR;
#pragma	ioport	Port_0_4_DriveMode_2_ADDR:	0x3
BYTE			Port_0_4_DriveMode_2_ADDR;
#pragma	ioport	Port_0_4_GlobalSelect_ADDR:	0x2
BYTE			Port_0_4_GlobalSelect_ADDR;
#pragma	ioport	Port_0_4_IntCtrl_0_ADDR:	0x102
BYTE			Port_0_4_IntCtrl_0_ADDR;
#pragma	ioport	Port_0_4_IntCtrl_1_ADDR:	0x103
BYTE			Port_0_4_IntCtrl_1_ADDR;
#pragma	ioport	Port_0_4_IntEn_ADDR:	0x1
BYTE			Port_0_4_IntEn_ADDR;
#define Port_0_4_MASK 0x10
